# cc -Wall -Wextra -Werror -c main.c -o main.o
# ERROR: file push_swap.h not found
# CORRECTION 1
# cc -Wall -Wextra -Werror -I.include -c main.c -o main.o
# ERROR: file libft.h not found
# CORRECTION 2
# cc -Wall -Wextra -Werror -I.include -I.libft/src -c main.c -o main.o
# SUCCESS
# => main.o




# cc -Wall -Wextra -Werror -c test.c -o test.o
# => test.o


